

var SuperWokDatabase = SuperWokDatabase  || {};  //Initialise Namespace

SuperWokDatabase.MAP_DETAILS = persistence.define('MAP_DETAILS',{
    ADDRESS:"TEXT",
	PAGE_REFERENCE : "TEXT",
    EXPIRED:"TEXT"
});
SuperWokDatabase.CUSTOMER_DETAILS = persistence.define('CUSTOMER_DETAILS',{
    CUSTOMER_ID:"TEXT",
    NAME:"TEXT",
    FIRST_NAME:"TEXT",
    FAMILY_NAME:"TEXT",
    PHONE_NUMBER:"NUMBER",
    ADDRESS_ONE:"TEXT",
    ADDRESS_TWO:"TEXT",
    ADDRESS_THREE:"TEXT",
    DELIVERY_CHARGE:"INT",
    NO_OF_ORDER:"INT",
    JOIN_TIME:"INT",
    LAST_ORDERED_TIME:"INT",
    PAGE_REFERENCE : "TEXT",
    EXPIRED:"TEXT"
});
SuperWokDatabase.ITEM_CATEGORY = persistence.define('ITEM_CATEGORY',{
    ITEM_CATEGORY_ID:"TEXT",
    ITEM_CATEGORY_SORT_CODE:"TEXT",
    ITEM_CATEGORY_NAME:"TEXT",
    ITEM_CATEGORY_FULL_DESCRIPTION:"TEXT",
    EXPIRED:"TEXT"
});
SuperWokDatabase.ITEM = persistence.define('ITEM',{
    ITEM_ID:"TEXT",
    ITEM_CODE:"TEXT",
    ITEM_NAME:"TEXT",
    ITEM_PRICE:"NUMERIC",
    ITEM_FULL_DESCRIPTION:"TEXT",
    ITEM_CHINESE_NAME:"TEXT",
    EXPIRED:"TEXT"
});
SuperWokDatabase.ORDER_TYPE_CATEGORY = persistence.define('ORDER_TYPE_CATEGORY',{
    ORDER_TYPE_CATEGORY_ID:"TEXT",
    ORDER_TYPE_CATEGORY_CODE:"TEXT",
    ORDER_TYPE_CATEGORY_NAME:"TEXT",
    EXPIRED:"TEXT"
});
SuperWokDatabase.ORDER_STATUS = persistence.define('ORDER_STATUS',{
    ORDER_STATUS_ID:"TEXT",
    ORDER_STATUS_CODE:"TEXT",
    ORDER_STATUS_NAME:"TEXT",
    EXPIRED:"TEXT"
});
SuperWokDatabase.PAY_STATUS = persistence.define('PAY_STATUS',{
    PAY_STATUS_ID:"TEXT",
    PAY_STATUS_CODE:"TEXT",
    PAY_STATUS_NAME:"TEXT",
    EXPIRED:"TEXT"
});
SuperWokDatabase.ORDER_DATA = persistence.define('ORDER_DATA',{

    ORDER_ID:"INT",
    TODAY_ID:"INT",
    ORDER_TIME:"INT",
    ORDER_FINISHED:"TEXT",
    ORDER_PAIED:"TEXT",
    ORDER_CANCELLED:"TEXT",
    NO_OF_ORDERED_ITEM:"TEXT",
    ORDER_TOTAL_PRICE:"NUMERIC",
    EXPIRED:"TEXT"

});
SuperWokDatabase.ORDERED_ITEM = persistence.define('ORDERED_ITEM',{
    ORDERED_ITEM_ID:"TEXT",
    ORDERED_ITEM_TIME:"INT",
    ORDERED_ITEM_QUANTITY:"TEXT",
    ORDERED_ITEM_MODIFY_DETAILS:"TEXT",
    EXPIRED:"TEXT"
});
SuperWokDatabase.ITEM_CATEGORY.hasMany("ITEM_ITEM_CATEGORY_ID", SuperWokDatabase.ITEM, "ITEM_CATEGORY_ID");
SuperWokDatabase.ORDER_TYPE_CATEGORY.hasMany("ORDER_ORDER_TYPE_CATEGORY_ID", SuperWokDatabase.ORDER_DATA, "ORDER_TYPE_CATEGORY_ID");
SuperWokDatabase.ORDER_STATUS.hasMany("ORDER_ORDER_STATUS_ID", SuperWokDatabase.ORDER_DATA, "ORDER_STATUS_ID");
SuperWokDatabase.PAY_STATUS.hasMany("ORDER_PAY_STATUS_ID", SuperWokDatabase.ORDER_DATA, "PAY_STATUS_ID");
SuperWokDatabase.ITEM.hasMany("ORDERED_ITEM_ITEM_ID", SuperWokDatabase.ORDERED_ITEM, "ITEM_ID");
SuperWokDatabase.ORDER_DATA.hasMany("ORDERED_ITEM_ITEM_ID", SuperWokDatabase.ORDERED_ITEM, "ORDER_DATA_ID");
SuperWokDatabase.CUSTOMER_DETAILS.hasMany("CUSTOMER_DETAIL_ID_ORDERED_DATA", SuperWokDatabase.ORDER_DATA, "CUSTOMER_DETAIL_ID");
